image: node

variables:
  CENTOS_IP: '123456789'

stages:
  - echo
  - build
  - deploy

echo-stage:
  stage: echo
  image: node
  tags:
    - 7-react-admin-ts-runner
  script:
    - echo ${CENTOS_IP}

build-stage:
  stage: build
  image: node
  only:
    - master
  tags:
    - 7-react-admin-ts-runner
  script:
    - rm -rf 7-react-admin-ts
    - git clone https://gitlab.com/woow_wu7/7-react-admin-ts.git
    - cd 7-react-admin-ts/
    - ls
    - npm install
    - npm run build
  # artifacts:
  #   expire_in: 1 week
  #   paths: 
  #     - $DIST_DIR

deploy-stage:
  stage: deploy
  image: node
  only:
    - master
  tags:
    - 7-react-admin-ts-runner
  script: 
    - echo "successed"