image: node

variables:
  CENTOS_IP: '123456789'

stages:
  - log
  - build
  - deploy

log-stage:
  stage: log
  image: node
  script:
    - echo ${CENTOS_IP}
    - npm -v
    - node -v
    - git --help
    - ls
build-stage:
  stage: build
  image: node
  only:
    - master
  tags:
    - 7-react-admin-ts-runner
  script:
    - echo 1
    - echo 2
    # - rm -rf 7-react-admin-ts
    # - npm install cnpm -g --registry=https://registry.npm.taobao.org
    # - git clone https://gitlab.com/woow_wu7/7-react-admin-ts.git
    # - cd 7-react-admin-ts/
    # - cnpm install
    # - cnpm run build
  # artifacts:
  #   expire_in: 1 week
  #   paths: 
  #     - $DIST_DIR

deploy-stage:
  stage: deploy
  image: node
  only:
    - master
  tags:
    - 7-react-admin-ts-runner
  script: 
    - console.log(1)