image: node

stages:
  - build

build-stage:
  stage: build
  image: node
  tags:
    - 7-react-admin-ts-runner
  script:
    - rm -rf 7-react-admin-ts
    - npm install cnpm -g --registry=https://registry.npm.taobao.org
    - git clone https://gitlab.com/woow_wu7/7-react-admin-ts.git
    - cd 7-react-admin-ts
    - cnpm install
    - cnpm run build
